language: python

python:
- "2.7"

services:
- postgresql

before_script:
- psql -c 'create database travis_ci_test;' -U postgres

install:
- pip install web.py
- pip install psycopg2
- pip install paste
- pip install coverage
- pip install codeclimate-test-reporter

script: 
- nosetests --with-coverage -v
- codeclimate-test-reporter
